name: audio_db_app
description: Application musicale utilisant l'API TheAudioDB
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # Navigation
  go_router: ^12.0.0
  
  # State management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Network
  retrofit: ^4.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600